"""Governed Research candidate registry for RL-CANDIDATE-01."""

from .candidate import (
    CANDIDATE_EVENT_IDENTITY_SCHEMA,
    CANDIDATE_IDENTITY_SCHEMA,
    CANDIDATE_SCHEMA,
    EVALUATION_IDENTITY_SCHEMA,
    PROMOTION_REQUEST_IDENTITY_SCHEMA,
    PROMOTION_REQUEST_SCHEMA,
    CandidateValidationError,
    canonical_json_bytes,
    compute_candidate_id,
    compute_evaluation_run_id,
    dataset_requirement_id,
    evaluation_run_identity,
    sha256_json,
    validate_candidate,
)
from .registry import (
    CANDIDATE_STATES,
    LEGAL_TRANSITIONS,
    PROMOTION_REQUEST_STATES,
    TERMINAL_STATES,
    PublicationResult,
    RegistryError,
    candidate_event_identity,
    compute_event_id,
    compute_promotion_request_id,
    project_candidate_states,
    promotion_request_identity,
    publish_candidate,
    validate_promotion_request,
)

__all__ = [
    "CANDIDATE_EVENT_IDENTITY_SCHEMA",
    "CANDIDATE_IDENTITY_SCHEMA",
    "CANDIDATE_SCHEMA",
    "CANDIDATE_STATES",
    "EVALUATION_IDENTITY_SCHEMA",
    "LEGAL_TRANSITIONS",
    "PROMOTION_REQUEST_IDENTITY_SCHEMA",
    "PROMOTION_REQUEST_SCHEMA",
    "PROMOTION_REQUEST_STATES",
    "TERMINAL_STATES",
    "CandidateValidationError",
    "PublicationResult",
    "RegistryError",
    "candidate_event_identity",
    "canonical_json_bytes",
    "compute_candidate_id",
    "compute_evaluation_run_id",
    "compute_event_id",
    "compute_promotion_request_id",
    "dataset_requirement_id",
    "evaluation_run_identity",
    "project_candidate_states",
    "promotion_request_identity",
    "publish_candidate",
    "sha256_json",
    "validate_candidate",
    "validate_promotion_request",
]
