"""
Database Models - SQLAlchemy models for PostgreSQL time-series storage
Stores: trades, signals, portfolio snapshots, metrics, performance data
"""

from datetime import datetime
from sqlalchemy import (
    create_engine, Column, String, Float, Integer, DateTime, 
    Boolean, JSON, ForeignKey, Index, func
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, Session
import json

Base = declarative_base()

class Signal(Base):
    """Trading signals generated by system"""
    __tablename__ = 'signals'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    symbol = Column(String(20), index=True)
    action = Column(String(10))  # BUY, SELL, HOLD
    confidence = Column(Float)  # 0-1
    position_size = Column(Float)
    entry_price = Column(Float, nullable=True)
    stop_loss = Column(Float, nullable=True)
    take_profit = Column(Float, nullable=True)
    regime = Column(String(20), nullable=True)
    has_anomalies = Column(Boolean, default=False)
    components = Column(JSON)  # Strategy, regime, RL signals
    reason = Column(String(500))
    
    __table_args__ = (
        Index('ix_symbol_timestamp', 'symbol', 'timestamp'),
        Index('ix_action', 'action'),
    )


class Trade(Base):
    """Executed trades with P&L"""
    __tablename__ = 'trades'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    symbol = Column(String(20), index=True)
    entry_timestamp = Column(DateTime)
    exit_timestamp = Column(DateTime, nullable=True)
    entry_price = Column(Float)
    exit_price = Column(Float, nullable=True)
    position_size = Column(Float)
    direction = Column(String(5))  # LONG, SHORT
    pnl = Column(Float, nullable=True)
    pnl_pct = Column(Float, nullable=True)
    status = Column(String(10))  # OPEN, CLOSED
    strategy = Column(String(50))
    entry_reason = Column(String(500))
    exit_reason = Column(String(500), nullable=True)
    exit_type = Column(String(20), nullable=True)  # TP, SL, EXIT
    fees = Column(Float, default=0)
    slippage = Column(Float, default=0)
    
    __table_args__ = (
        Index('ix_symbol_status', 'symbol', 'status'),
        Index('ix_entry_exit', 'entry_timestamp', 'exit_timestamp'),
    )


class PortfolioSnapshot(Base):
    """Portfolio state snapshots for performance tracking"""
    __tablename__ = 'portfolio_snapshots'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    total_value = Column(Float)
    cash = Column(Float)
    invested = Column(Float)
    total_pnl = Column(Float)
    total_pnl_pct = Column(Float)
    max_drawdown = Column(Float)
    max_drawdown_pct = Column(Float)
    positions = Column(JSON)  # {symbol: {qty, entry, current_price, pnl}}
    allocation = Column(JSON)  # {symbol: weight}
    
    __table_args__ = (
        Index('ix_timestamp', 'timestamp'),
    )


class DailyMetrics(Base):
    """Daily performance metrics"""
    __tablename__ = 'daily_metrics'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(DateTime, index=True)  # Start of day
    daily_return = Column(Float)
    daily_pnl = Column(Float)
    total_return = Column(Float)
    sharpe_ratio = Column(Float)
    sortino_ratio = Column(Float)
    calmar_ratio = Column(Float)
    max_drawdown = Column(Float)
    max_drawdown_pct = Column(Float)
    win_rate = Column(Float)
    profit_factor = Column(Float)
    trades_count = Column(Integer)
    win_trades = Column(Integer)
    loss_trades = Column(Integer)
    avg_win = Column(Float)
    avg_loss = Column(Float)
    
    __table_args__ = (
        Index('ix_date', 'date'),
    )


class StrategyPerformance(Base):
    """Per-strategy performance metrics"""
    __tablename__ = 'strategy_performance'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    strategy_name = Column(String(50), index=True)
    total_trades = Column(Integer)
    winning_trades = Column(Integer)
    losing_trades = Column(Integer)
    win_rate = Column(Float)
    total_pnl = Column(Float)
    avg_win = Column(Float)
    avg_loss = Column(Float)
    profit_factor = Column(Float)
    sharpe_ratio = Column(Float)
    max_drawdown = Column(Float)
    consecutive_wins = Column(Integer)
    consecutive_losses = Column(Integer)
    
    __table_args__ = (
        Index('ix_strategy_timestamp', 'strategy_name', 'timestamp'),
    )


class AnomalyEvent(Base):
    """Market anomalies detected"""
    __tablename__ = 'anomaly_events'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    symbol = Column(String(20), index=True)
    anomaly_type = Column(String(50))  # volume_spike, price_gap, etc
    severity = Column(String(10))  # low, medium, high
    score = Column(Float)  # 0-1 anomaly score
    description = Column(String(500))
    price_at_time = Column(Float)
    volume_at_time = Column(Float)
    resolution = Column(String(500), nullable=True)
    
    __table_args__ = (
        Index('ix_symbol_timestamp', 'symbol', 'timestamp'),
    )


class RegimeChange(Base):
    """Market regime changes detected"""
    __tablename__ = 'regime_changes'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    previous_regime = Column(String(20))
    new_regime = Column(String(20))
    confidence = Column(Float)
    trigger_factors = Column(JSON)  # What caused the change
    market_condition = Column(String(500))


class Backtest(Base):
    """Backtest results for strategy validation"""
    __tablename__ = 'backtests'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    backtest_name = Column(String(100))
    strategy_name = Column(String(50))
    symbol = Column(String(20))
    start_date = Column(DateTime)
    end_date = Column(DateTime)
    initial_capital = Column(Float)
    final_value = Column(Float)
    total_return = Column(Float)
    sharpe_ratio = Column(Float)
    sortino_ratio = Column(Float)
    calmar_ratio = Column(Float)
    max_drawdown = Column(Float)
    total_trades = Column(Integer)
    win_rate = Column(Float)
    profit_factor = Column(Float)
    avg_win = Column(Float)
    avg_loss = Column(Float)
    trades_data = Column(JSON)  # Array of trade details
    
    __table_args__ = (
        Index('ix_backtest_timestamp', 'timestamp'),
    )


class DatabaseManager:
    """Database connection and operations manager"""
    
    def __init__(self, database_url: str = None):
        """Initialize database connection"""
        if database_url is None:
            database_url = "postgresql://user:password@localhost:5432/crypto_trading"
        
        self.engine = create_engine(database_url, echo=False)
        self.Session = None
    
    def create_tables(self):
        """Create all tables"""
        Base.metadata.create_all(self.engine)
    
    def get_session(self) -> Session:
        """Get database session"""
        from sqlalchemy.orm import sessionmaker
        if self.Session is None:
            self.Session = sessionmaker(bind=self.engine)
        return self.Session()
    
    def add_signal(self, signal_data: dict) -> Signal:
        """Add trading signal to database"""
        session = self.get_session()
        try:
            signal = Signal(**signal_data)
            session.add(signal)
            session.commit()
            return signal
        finally:
            session.close()
    
    def add_trade(self, trade_data: dict) -> Trade:
        """Add executed trade"""
        session = self.get_session()
        try:
            trade = Trade(**trade_data)
            session.add(trade)
            session.commit()
            return trade
        finally:
            session.close()
    
    def update_trade(self, trade_id: int, update_data: dict):
        """Update trade (close it)"""
        session = self.get_session()
        try:
            trade = session.query(Trade).filter_by(id=trade_id).first()
            if trade:
                for key, value in update_data.items():
                    setattr(trade, key, value)
                session.commit()
        finally:
            session.close()
    
    def add_portfolio_snapshot(self, snapshot_data: dict) -> PortfolioSnapshot:
        """Add portfolio state snapshot"""
        session = self.get_session()
        try:
            snapshot = PortfolioSnapshot(**snapshot_data)
            session.add(snapshot)
            session.commit()
            return snapshot
        finally:
            session.close()
    
    def get_daily_metrics(self, days: int = 30):
        """Get last N days metrics"""
        session = self.get_session()
        try:
            metrics = session.query(DailyMetrics)\
                .order_by(DailyMetrics.date.desc())\
                .limit(days).all()
            return metrics
        finally:
            session.close()
    
    def get_strategy_performance(self, strategy_name: str = None):
        """Get strategy performance"""
        session = self.get_session()
        try:
            query = session.query(StrategyPerformance)
            if strategy_name:
                query = query.filter_by(strategy_name=strategy_name)
            return query.order_by(StrategyPerformance.timestamp.desc()).first()
        finally:
            session.close()
    
    def get_open_trades(self, symbol: str = None):
        """Get open trades"""
        session = self.get_session()
        try:
            query = session.query(Trade).filter_by(status='OPEN')
            if symbol:
                query = query.filter_by(symbol=symbol)
            return query.all()
        finally:
            session.close()
    
    def get_recent_signals(self, symbol: str = None, limit: int = 100):
        """Get recent signals"""
        session = self.get_session()
        try:
            query = session.query(Signal)
            if symbol:
                query = query.filter_by(symbol=symbol)
            return query.order_by(Signal.timestamp.desc()).limit(limit).all()
        finally:
            session.close()


print("[DATABASE MODELS] PostgreSQL models loaded")
