"""observability/operator_boot_coordinator.py — O-02W-C boot/identity/
manifest-gating coordinator (Correction G, R2 MASTER review round 2).

R1 scattered the bootstrap identity, the manifest-published flag, and the
manifest retry logic across a closure (`_op_try_publish_manifest`) plus
loose `nonlocal` variables inside `core/advisor_loop.py`'s bootstrap
block — impossible to unit-test directly, and vulnerable to silently
redefining `boot_timestamp_utc` to "now" on a delayed successful retry
(`write_runtime_manifest()` used to recompute `_iso_utc(now_fn())` fresh
on every call).

This module extracts that logic into one small, directly-testable,
production-used object: `OperatorBootCoordinator`. It owns:

- `process_instance_id` — generated exactly once, via
  `observability.process_identity.generate_process_instance_id()`.
- `boot_timestamp_utc` — captured exactly once, at construction, via
  `now_fn()`. Every manifest retry for this SAME coordinator instance
  (i.e. the SAME process lifetime) reuses this exact original value —
  never recomputed.
- `source_evidence` — captured exactly once via the injected
  `capture_source_evidence_fn`.
- `manifest_published` — sticky success flag; once True, retries stop.
- `try_publish_manifest()` — bounded retry (safe to call once per cycle);
  never raises (fail-passive, ADR-0007).
- `snapshot_publication_allowed()` — the gate: the canonical operator
  snapshot may only be written once the manifest for THIS
  `process_instance_id` has been published successfully at least once.

`core/advisor_loop.py`'s bootstrap block constructs exactly one instance
of this coordinator and uses it for both the manifest-publish attempt and
the snapshot-publication gate — the same object S-03's
`_runtime_provenance_inputs()` and the operator snapshot builder are fed
`process_instance_id` from, so all three outputs (S-03, manifest,
snapshot) carry the same non-tautological identity by construction, not
by test-only wiring.
"""

from __future__ import annotations

import time
from typing import Any, Callable, Optional

from observability.json_logger import get_logger
from observability.process_identity import generate_process_instance_id

_log = get_logger("observability.operator_boot_coordinator")


def _iso_utc(ts: float) -> str:
    import datetime as _dt

    return (
        _dt.datetime.fromtimestamp(ts, tz=_dt.timezone.utc)
        .isoformat(timespec="seconds")
        .replace("+00:00", "Z")
    )


class OperatorBootCoordinator:
    """Sole owner of one advisor process's boot identity + manifest gate.

    Construct exactly once per process lifetime (a fresh instance =
    a simulated restart, yielding a new `process_instance_id` AND a new
    `boot_timestamp_utc`, consistently propagated everywhere this
    instance is threaded).
    """

    def __init__(
        self,
        *,
        now_fn: Callable[[], float] = time.time,
        write_manifest_fn: Optional[Callable[..., bool]] = None,
        capture_source_evidence_fn: Optional[Callable[[], Any]] = None,
        generate_identity_fn: Callable[[], str] = generate_process_instance_id,
    ) -> None:
        self._now_fn = now_fn
        if write_manifest_fn is None:
            from observability.operator_runtime_manifest import write_runtime_manifest

            write_manifest_fn = write_runtime_manifest
        self._write_manifest_fn = write_manifest_fn

        # Identity + boot timestamp: captured exactly once, here, at
        # construction — never regenerated by any consumer.
        self.process_instance_id: str = generate_identity_fn()
        self.boot_timestamp_utc: str = _iso_utc(self._now_fn())

        self.source_evidence: Optional[Any] = None
        if capture_source_evidence_fn is not None:
            try:
                self.source_evidence = capture_source_evidence_fn()
            except Exception as exc:  # pragma: no cover - defensive
                _log.debug(
                    "[OperatorBootCoordinator] capture_source_evidence a échoué "
                    "(non bloquant): %s",
                    exc,
                )
                self.source_evidence = None

        self.manifest_published: bool = False
        self.manifest_publish_attempts: int = 0

    def try_publish_manifest(self) -> bool:
        """Attempt to publish the runtime manifest for this process's
        identity. Sticky: once published, subsequent calls are no-ops
        that return True immediately. Never raises (fail-passive)."""

        if self.manifest_published:
            return True
        self.manifest_publish_attempts += 1
        try:
            source_sha = getattr(self.source_evidence, "source_sha", None)
            ok = self._write_manifest_fn(
                process_instance_id=self.process_instance_id,
                source_sha=source_sha,
                boot_timestamp_utc=self.boot_timestamp_utc,
            )
        except Exception as exc:
            _log.debug(
                "[OperatorBootCoordinator] Publication manifest échouée "
                "(non bloquant): %s",
                exc,
            )
            ok = False
        self.manifest_published = bool(ok)
        return self.manifest_published

    def snapshot_publication_allowed(self) -> bool:
        """The canonical operator snapshot gate (§14.1): no domain
        snapshot for this process may be written until this process's own
        manifest has been published successfully at least once."""

        return self.manifest_published


__all__ = ["OperatorBootCoordinator"]
