import type { BurnInStatusSnapshot } from "../lib/burnInStatusTypes";

export function burnInFixture(): BurnInStatusSnapshot {
  return {
    schema_version: "1.0.0",
    product: "BurnInStatusSnapshot",
    domain: "burn_in",
    authority: "PPL_AUTHORITY_PRESENTATION",
    mode: "READ_ONLY",
    generated_at_utc: "2026-10-01T20:00:00Z",
    source_updated_at_utc: "2026-10-01T19:59:50Z",
    paper_epoch_id: "BURN-IN-EPOCH-01-20260926T064144Z",
    epoch_created_at_utc: "2026-09-27T02:41:07Z",
    source_code_sha: "1".repeat(40),
    config_snapshot_hash: "2".repeat(64),
    ppl_stream_sha256: "3".repeat(64),
    scientific_t0: {
      status: "PRESENT",
      value_utc: "2026-09-27T03:06:03.086973Z",
      source: "WEB_DIR_01_D1_GOVERNANCE_CONTRACT",
    },
    event_count: 7,
    last_sequence: 7,
    event_counts: {
      EPOCH_CREATED: 1,
      POSITION_OPENED: 3,
      POSITION_CLOSED: 1,
      POSITION_UNRESOLVED: 1,
      RECOVERY_COMPLETED: 1,
    },
    lifecycle_counts: { open: 1, closed: 1, unresolved: 1, total: 3 },
    last_event: {
      sequence: 7,
      event_type: "RECOVERY_COMPLETED",
      timestamp_utc: "2026-10-01T19:59:50Z",
      trade_id: null,
      decision_id: null,
    },
    open_lifecycles: [{
      trade_id: "trade-open",
      decision_id: "decision-2",
      symbol: "ETH/USDT",
      side: "SHORT",
      principal_usd: 10,
      entry_price: 200,
      entry_fee_usd: 0.01,
      opened_sequence: 4,
      opened_at_utc: "2026-10-01T18:00:00Z",
      age_seconds: 7200,
      tp_price: 190,
      sl_price: 205,
      timeout_at_utc: "2026-10-01T20:30:00Z",
      recovery_eligible_until_utc: "2026-10-02T05:30:00Z",
      deadline_state: "BEFORE_TIMEOUT",
    }],
    lifecycle_history: [
      {
        trade_id: "trade-unresolved", open_decision_id: null, terminal_decision_id: null,
        symbol: "SOL/USDT", side: "LONG", principal_usd: 10, entry_price: 50,
        entry_fee_usd: 0.01, opened_sequence: 5, opened_at_utc: "2026-10-01T18:10:00Z",
        status: "UNRESOLVED", terminal_sequence: 6, terminal_at_utc: "2026-10-01T18:20:00Z",
        exit_price: null, exit_fee_usd: null, gross_pnl_usd: null, net_realized_pnl_usd: null,
        unresolved_reason: "RECOVERY_PRICE_UNAVAILABLE", duration_seconds: 600,
      },
      {
        trade_id: "trade-open", open_decision_id: "decision-2", terminal_decision_id: null,
        symbol: "ETH/USDT", side: "SHORT", principal_usd: 10, entry_price: 200,
        entry_fee_usd: 0.01, opened_sequence: 4, opened_at_utc: "2026-10-01T18:00:00Z",
        status: "OPEN", terminal_sequence: null, terminal_at_utc: null,
        exit_price: null, exit_fee_usd: null, gross_pnl_usd: null, net_realized_pnl_usd: null,
        unresolved_reason: null, duration_seconds: null,
      },
      {
        trade_id: "trade-closed", open_decision_id: "decision-1", terminal_decision_id: "decision-close",
        symbol: "BTC/USDT", side: "LONG", principal_usd: 10, entry_price: 100,
        entry_fee_usd: 0.01, opened_sequence: 2, opened_at_utc: "2026-10-01T17:00:00Z",
        status: "CLOSED", terminal_sequence: 3, terminal_at_utc: "2026-10-01T17:30:00Z",
        exit_price: 110, exit_fee_usd: 0.01, gross_pnl_usd: 1, net_realized_pnl_usd: 0.98,
        unresolved_reason: null, duration_seconds: 1800,
      },
    ],
    history_order: "OPEN_SEQUENCE_DESC",
    frozen_config: {
      snapshot_schema: "BURN_IN_EXPERIMENT_CONFIG_V1",
      snapshot_sha256: "2".repeat(64),
      runtime_source_sha: "1".repeat(40),
      pb_max_positions: "2",
      paper_portfolio_brain_level: "a",
      mexc_sim_max_position_usd: "10",
      mexc_sim_max_age_h: "8",
      paper_lifecycle_authority: "PPL_AUTHORITY",
    },
    finalization: {
      state: "NOT_AVAILABLE",
      reason: "NO_GOVERNED_FINALIZATION_ARTIFACT_SUPPLIED",
    },
    snapshot_age_s: 4,
    freshness_classification: "FRESH",
  };
}
