// ── crossStack.compat.test.ts — O-02W-D3 LOCAL CROSS-STACK COMPATIBILITY GATE
//
// Reads the EXACT JSON bodies generated by the real Python producer/reader/
// API path (tests/cross_stack/generate_fixtures.py — never a handwritten
// "golden" fixture) and proves they are accepted, unchanged, by the real
// frontend validator (`validateOperatorSnapshot`) and rendered by the real
// cockpit (`App`) with no compatibility transform in between.
//
// If the fixtures directory does not exist (e.g. a plain `npm test` run
// outside the dedicated cross-stack CI job, which generates it first), this
// whole file is skipped rather than failing — the existing `frontend-ci.yml`
// job never runs the Python fixture generator and must not be coupled to it.

import { describe, it, expect, vi, afterEach } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import App from "../App";
import { validateOperatorSnapshot } from "../lib/snapshotValidation";
import type { OperatorSnapshot, ApiStructuredError } from "../types";

const FIXTURES_DIR =
  process.env.CROSS_STACK_FIXTURES_DIR ?? path.resolve(__dirname, "../../.cross-stack-fixtures");

const HAS_FIXTURES = existsSync(FIXTURES_DIR);

interface GeneratedFixture {
  http_status: number;
  body: unknown;
  _proof?: Record<string, number>;
}

function loadFixture(name: string): GeneratedFixture {
  const raw = readFileSync(path.join(FIXTURES_DIR, `${name}.json`), "utf-8");
  return JSON.parse(raw) as GeneratedFixture;
}

function jsonResponse(body: unknown, status: number) {
  return { ok: status >= 200 && status < 300, status, json: async () => body } as Response;
}

describe.skipIf(!HAS_FIXTURES)("cross-stack compatibility (real Python producer -> real API -> frontend)", () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it("A: accepts the exact producer-generated JSON unchanged and renders every cockpit view", async () => {
    const fixture = loadFixture("A_minimal_canonical");
    expect(fixture.http_status).toBe(200);

    // The admission gate itself, run directly against the untouched body —
    // no reshaping performed by this test before validation.
    expect(validateOperatorSnapshot(fixture.body)).toBe(true);

    vi.stubGlobal("fetch", vi.fn().mockResolvedValue(jsonResponse(fixture.body, 200)));
    render(<App />);
    await waitFor(() => expect(screen.getByTestId("overview-view")).toBeInTheDocument());

    fireEvent.click(screen.getByTestId("tab-portfolio"));
    expect(screen.getByTestId("portfolio-view")).toBeInTheDocument();

    fireEvent.click(screen.getByTestId("tab-decisions"));
    expect(screen.getByTestId("decisions-view")).toBeInTheDocument();

    fireEvent.click(screen.getByTestId("tab-system"));
    expect(screen.getByTestId("system-view")).toBeInTheDocument();
  });

  it("B: UNKNOWN mode snapshot is accepted and rendered honestly, never defaulted to PAPER", async () => {
    const fixture = loadFixture("B_unknown_mode_fail_closed");
    expect(fixture.http_status).toBe(200);
    expect(fixture._proof?.wallet_get_balance_calls).toBe(0);
    expect(fixture._proof?.wallet_capital_x_reads).toBe(0);
    expect(validateOperatorSnapshot(fixture.body)).toBe(true);

    vi.stubGlobal("fetch", vi.fn().mockResolvedValue(jsonResponse(fixture.body, 200)));
    render(<App />);
    await waitFor(() => expect(screen.getByTestId("mode-badge")).toHaveAttribute("data-mode", "UNKNOWN"));
  });

  it("C: PAPER vs REAL account separation and UNAVAILABLE price/PnL survive unchanged into the cockpit", async () => {
    const fixture = loadFixture("C_portfolio_semantics");
    expect(fixture.http_status).toBe(200);
    expect(validateOperatorSnapshot(fixture.body)).toBe(true);
    const snapshot = fixture.body as OperatorSnapshot;
    expect(snapshot.portfolio.paper_equity_usd.semantics).toBe("PRESENT");
    expect(snapshot.portfolio.real_account_equity_usd.semantics).toBe("PRESENT");
    expect(snapshot.portfolio.paper_equity_usd.value).not.toBe(snapshot.portfolio.real_account_equity_usd.value);

    vi.stubGlobal("fetch", vi.fn().mockResolvedValue(jsonResponse(fixture.body, 200)));
    render(<App />);
    await waitFor(() => expect(screen.getByTestId("overview-view")).toBeInTheDocument());
    fireEvent.click(screen.getByTestId("tab-portfolio"));
    const text = screen.getByTestId("portfolio-view").textContent ?? "";
    expect(text).toMatch(/UNAVAILABLE/);
  });

  it("D: authority mapping is accepted as-is, and a mutated authority mapping is rejected by the frontend validator", async () => {
    const fixture = loadFixture("D_decision_authority");
    expect(fixture.http_status).toBe(200);
    expect(validateOperatorSnapshot(fixture.body)).toBe(true);

    const snapshot = fixture.body as OperatorSnapshot;
    const decisions = snapshot.decision_pipeline.per_symbol_decisions;
    for (const d of decisions) {
      expect(d.is_actionable.authority).toBe("EXECUTION_AUTHORITY");
      expect(d.trade_allowed.authority).toBe("OBSERVATIONAL_TELEMETRY");
      expect(d.first_blocker.authority).toBe("OBSERVATIONAL_TELEMETRY");
    }

    // Mutate ONLY the authority tag on a deep copy — the real per-field
    // mapping enforcement must reject it outright, never normalize it.
    const mutated = JSON.parse(JSON.stringify(fixture.body)) as OperatorSnapshot;
    mutated.decision_pipeline.per_symbol_decisions[0].is_actionable.authority = "OBSERVATIONAL_TELEMETRY";
    expect(validateOperatorSnapshot(mutated)).toBe(false);
  });

  it("E: a previous-instance snapshot is accepted and visibly presented as LAST_KNOWN, never CURRENT_INSTANCE", async () => {
    const fixture = loadFixture("E_previous_instance");
    expect(fixture.http_status).toBe(200);
    expect(validateOperatorSnapshot(fixture.body)).toBe(true);
    const snapshot = fixture.body as OperatorSnapshot;
    expect(snapshot.instance_relation).toBe("PREVIOUS_INSTANCE");
    expect(snapshot.runtime_state).toBe("LAST_KNOWN");
    expect(snapshot.stale_reason).toBe("PRODUCER_RESTARTED");

    vi.stubGlobal("fetch", vi.fn().mockResolvedValue(jsonResponse(fixture.body, 200)));
    render(<App />);
    await waitFor(() => expect(screen.getByTestId("overview-view")).toBeInTheDocument());
    expect(screen.getByTestId("instance-relation")).toHaveTextContent("PREVIOUS_INSTANCE");
    expect(screen.getByTestId("runtime-state")).toHaveTextContent("LAST_KNOWN");
  });

  it("F: a governed 503 from a malformed producer artifact is surfaced honestly, never as a fabricated success", async () => {
    const fixture = loadFixture("F_failure_honesty");
    expect(fixture.http_status).toBe(503);
    const errorBody = fixture.body as ApiStructuredError;
    expect(errorBody.error_code).toBe("SNAPSHOT_UNSUPPORTED_SCHEMA_VERSION");

    vi.stubGlobal("fetch", vi.fn().mockResolvedValue(jsonResponse(fixture.body, 503)));
    render(<App />);
    await waitFor(() => expect(screen.getByTestId("snapshot-status-api-error")).toBeInTheDocument());
    expect(screen.getByTestId("no-snapshot")).toBeInTheDocument();
    expect(screen.queryByTestId("overview-view")).toBeNull();
  });
});
