// ── crossStack.compat.test.ts — O-02W-D3 LOCAL CROSS-STACK COMPATIBILITY GATE
//
// Reads the EXACT JSON bodies generated by the real Python producer/reader/
// API paths (tests/cross_stack generators — never handwritten "golden"
// fixtures) and proves they are accepted, unchanged, by the real frontend
// validators/cockpit. WEB-01-MARKET adds the separate CryptoRadar producer ->
// atomic artifact -> real API -> real MarketView path.
//
// If the fixtures directory does not exist (e.g. a plain `npm test` run
// outside the dedicated cross-stack CI job, which generates it first), this
// whole file is skipped rather than failing — the existing frontend-ci.yml
// job never runs the Python fixture generators and must not be coupled to it.

import { describe, it, expect, vi, afterEach } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import App from "../App";
import { MarketMicrostructureView } from "../views/MarketMicrostructureView";
import { validateMarketMicrostructureSnapshot } from "../lib/marketMicrostructureValidation";
import { MarketView } from "../views/MarketView";
import { validateOperatorSnapshot } from "../lib/snapshotValidation";
import { validateMarketRadarSnapshot } from "../lib/marketValidation";
import { validatePplComparisonSnapshot } from "../lib/pplComparisonValidation";
import { validateResearchLabSnapshot } from "../lib/researchLabValidation";
import { validateBurnInStatusSnapshot } from "../lib/burnInStatusValidation";
import { validateRuntimeServiceSnapshot } from "../lib/runtimeServiceValidation";
import type { OperatorSnapshot, ApiStructuredError } from "../types";

const FIXTURES_DIR =
  process.env.CROSS_STACK_FIXTURES_DIR ?? path.resolve(__dirname, "../../.cross-stack-fixtures");

const HAS_FIXTURES = existsSync(FIXTURES_DIR);

interface GeneratedFixture {
  http_status: number;
  body: unknown;
  _proof?: Record<string, unknown>;
}

function loadFixture(name: string): GeneratedFixture {
  const raw = readFileSync(path.join(FIXTURES_DIR, `${name}.json`), "utf-8");
  return JSON.parse(raw) as GeneratedFixture;
}

function jsonResponse(body: unknown, status: number) {
  return { ok: status >= 200 && status < 300, status, json: async () => body } as Response;
}

describe.skipIf(!HAS_FIXTURES)("cross-stack compatibility (real Python producer -> real API -> frontend)", () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it("A: accepts the exact producer-generated JSON unchanged and renders every canonical cockpit view", async () => {
    const fixture = loadFixture("A_minimal_canonical");
    expect(fixture.http_status).toBe(200);

    expect(validateOperatorSnapshot(fixture.body)).toBe(true);

    vi.stubGlobal("fetch", vi.fn().mockResolvedValue(jsonResponse(fixture.body, 200)));
    render(<App />);
    await waitFor(() => expect(screen.getByTestId("overview-view")).toBeInTheDocument());

    fireEvent.click(screen.getByTestId("tab-paper"));
    expect(screen.getByTestId("portfolio-view")).toBeInTheDocument();

    fireEvent.click(screen.getByTestId("tab-decisions"));
    expect(screen.getByTestId("decisions-view")).toBeInTheDocument();

    fireEvent.click(screen.getByTestId("tab-system"));
    expect(screen.getByTestId("system-view")).toBeInTheDocument();
  });

  it("B: UNKNOWN mode snapshot is accepted and rendered honestly, never defaulted to PAPER", async () => {
    const fixture = loadFixture("B_unknown_mode_fail_closed");
    expect(fixture.http_status).toBe(200);
    expect(fixture._proof?.wallet_get_balance_calls).toBe(0);
    expect(fixture._proof?.wallet_capital_x_reads).toBe(0);
    expect(validateOperatorSnapshot(fixture.body)).toBe(true);

    vi.stubGlobal("fetch", vi.fn().mockResolvedValue(jsonResponse(fixture.body, 200)));
    render(<App />);
    await waitFor(() => expect(screen.getByTestId("mode-badge")).toHaveAttribute("data-mode", "UNKNOWN"));
  });

  it("C: PAPER vs REAL account separation and UNAVAILABLE price/PnL survive unchanged into the cockpit", async () => {
    const fixture = loadFixture("C_portfolio_semantics");
    expect(fixture.http_status).toBe(200);
    expect(validateOperatorSnapshot(fixture.body)).toBe(true);
    const snapshot = fixture.body as OperatorSnapshot;
    expect(snapshot.portfolio.paper_equity_usd.semantics).toBe("PRESENT");
    expect(snapshot.portfolio.real_account_equity_usd.semantics).toBe("PRESENT");
    expect(snapshot.portfolio.paper_equity_usd.value).not.toBe(snapshot.portfolio.real_account_equity_usd.value);

    vi.stubGlobal("fetch", vi.fn().mockResolvedValue(jsonResponse(fixture.body, 200)));
    render(<App />);
    await waitFor(() => expect(screen.getByTestId("overview-view")).toBeInTheDocument());
    fireEvent.click(screen.getByTestId("tab-paper"));
    const text = screen.getByTestId("portfolio-view").textContent ?? "";
    expect(text).toMatch(/UNAVAILABLE/);
  });

  it("D: authority mapping is accepted as-is, and a mutated authority mapping is rejected by the frontend validator", async () => {
    const fixture = loadFixture("D_decision_authority");
    expect(fixture.http_status).toBe(200);
    expect(validateOperatorSnapshot(fixture.body)).toBe(true);

    const snapshot = fixture.body as OperatorSnapshot;
    const decisions = snapshot.decision_pipeline.per_symbol_decisions;
    for (const d of decisions) {
      expect(d.is_actionable.authority).toBe("EXECUTION_AUTHORITY");
      expect(d.trade_allowed.authority).toBe("OBSERVATIONAL_TELEMETRY");
      expect(d.first_blocker.authority).toBe("OBSERVATIONAL_TELEMETRY");
    }

    const mutated = JSON.parse(JSON.stringify(fixture.body)) as OperatorSnapshot;
    mutated.decision_pipeline.per_symbol_decisions[0].is_actionable.authority = "OBSERVATIONAL_TELEMETRY";
    expect(validateOperatorSnapshot(mutated)).toBe(false);
  });

  it("E: a previous-instance snapshot is accepted and visibly presented as LAST_KNOWN, never CURRENT_INSTANCE", async () => {
    const fixture = loadFixture("E_previous_instance");
    expect(fixture.http_status).toBe(200);
    expect(validateOperatorSnapshot(fixture.body)).toBe(true);
    const snapshot = fixture.body as OperatorSnapshot;
    expect(snapshot.instance_relation).toBe("PREVIOUS_INSTANCE");
    expect(snapshot.runtime_state).toBe("LAST_KNOWN");
    expect(snapshot.stale_reason).toBe("PRODUCER_RESTARTED");

    vi.stubGlobal("fetch", vi.fn().mockResolvedValue(jsonResponse(fixture.body, 200)));
    render(<App />);
    await waitFor(() => expect(screen.getByTestId("overview-view")).toBeInTheDocument());
    expect(screen.getByTestId("instance-relation")).toHaveTextContent("PREVIOUS_INSTANCE");
    expect(screen.getByTestId("runtime-state")).toHaveTextContent("LAST_KNOWN");
  });

  it("F: a governed 503 from a malformed producer artifact is surfaced honestly, never as a fabricated success", async () => {
    const fixture = loadFixture("F_failure_honesty");
    expect(fixture.http_status).toBe(503);
    const errorBody = fixture.body as ApiStructuredError;
    expect(errorBody.error_code).toBe("SNAPSHOT_UNSUPPORTED_SCHEMA_VERSION");

    vi.stubGlobal("fetch", vi.fn().mockResolvedValue(jsonResponse(fixture.body, 503)));
    render(<App />);
    await waitFor(() => expect(screen.getByTestId("snapshot-status-api-error")).toBeInTheDocument());
    expect(screen.getByTestId("no-snapshot")).toBeInTheDocument();
    expect(screen.queryByTestId("overview-view")).toBeNull();
  });

  it("G MARKET: exact CryptoRadar producer/API JSON is admitted unchanged and rendered by MarketView", async () => {
    const canonical = loadFixture("A_minimal_canonical");
    const market = loadFixture("G_market");
    expect(canonical.http_status).toBe(200);
    expect(market.http_status).toBe(200);
    expect(validateOperatorSnapshot(canonical.body)).toBe(true);
    expect(validateMarketRadarSnapshot(market.body)).toBe(true);
    expect(market._proof?.producer_authority).toBe("OBSERVATIONAL_TELEMETRY");
    expect(market._proof?.artifact_is_regular_file).toBe(true);

    const fetchMock = vi.fn().mockImplementation((input: RequestInfo | URL) => {
      const url = String(input);
      if (url === "/api/operator/v1/market") return Promise.resolve(jsonResponse(market.body, 200));
      if (url === "/api/operator/v1/snapshot") return Promise.resolve(jsonResponse(canonical.body, 200));
      return Promise.resolve(jsonResponse({ error_code: "UNEXPECTED_TEST_URL" }, 404));
    });
    vi.stubGlobal("fetch", fetchMock);

    render(<App />);
    await waitFor(() => expect(screen.getByTestId("overview-view")).toBeInTheDocument());
    fireEvent.click(screen.getByTestId("tab-market"));

    await waitFor(() => expect(screen.getByTestId("market-view")).toHaveTextContent("BTC/USDT"));
    expect(screen.getByTestId("market-freshness")).toHaveTextContent("FRESH");
    expect(screen.getByTestId("market-view")).toHaveTextContent("OBSERVATIONAL_TELEMETRY");
    expect(screen.getByTestId("market-view")).not.toHaveTextContent("Entry");
    expect(screen.getByTestId("market-view")).not.toHaveTextContent("Stop Loss");
    expect(screen.getByTestId("market-view")).not.toHaveTextContent("Take Profit");
    expect(fetchMock).toHaveBeenCalledWith("/api/operator/v1/market", { method: "GET" });
  });


  it("H WEB-02: exact comparator producer/API JSON preserves the raw divergence into the cockpit", async () => {
    const canonical = loadFixture("A_minimal_canonical");
    const ppl = loadFixture("H_ppl_comparison");
    expect(canonical.http_status).toBe(200);
    expect(ppl.http_status).toBe(200);
    expect(validateOperatorSnapshot(canonical.body)).toBe(true);
    expect(validatePplComparisonSnapshot(ppl.body)).toBe(true);
    expect(ppl._proof?.producer_authority).toBe("OBSERVATIONAL_TELEMETRY");
    expect(ppl._proof?.legacy_authority).toBe("PAPER_AUTHORITY");
    expect(ppl._proof?.shadow_authority).toBe("NONE");
    expect(ppl._proof?.raw_legacy_cash).toBe(99.99);
    expect(ppl._proof?.raw_ppl_cash).toBe(100);
    expect(ppl._proof?.producer_delta).toBeCloseTo(0.01);

    const fetchMock = vi.fn().mockImplementation((input: RequestInfo | URL) => {
      const url = String(input);
      if (url === "/api/operator/v1/ppl-comparison") {
        return Promise.resolve(jsonResponse(ppl.body, 200));
      }
      if (url === "/api/operator/v1/snapshot") {
        return Promise.resolve(jsonResponse(canonical.body, 200));
      }
      return Promise.resolve(jsonResponse({ error_code: "UNEXPECTED_TEST_URL" }, 404));
    });
    vi.stubGlobal("fetch", fetchMock);

    render(<App />);
    await waitFor(() => expect(screen.getByTestId("overview-view")).toBeInTheDocument());
    fireEvent.click(screen.getByTestId("tab-paper"));
    fireEvent.click(screen.getByTestId("tab-ppl"));

    await waitFor(() =>
      expect(screen.getByTestId("ppl-comparison-view")).toHaveTextContent("Legacy PAPER"),
    );
    const view = screen.getByTestId("ppl-comparison-view");
    expect(view).toHaveTextContent("99.99");
    expect(view).toHaveTextContent("100");
    expect(view).toHaveTextContent("0.01");
    expect(view).toHaveTextContent("DIFFERENT");
    expect(fetchMock).toHaveBeenCalledWith(
      "/api/operator/v1/ppl-comparison",
      { method: "GET" },
    );
  });

  it("I WEB-RL: exact Research publisher/API JSON remains non-authoritative and renders explicit evidence gaps", async () => {
    const canonical = loadFixture("A_minimal_canonical");
    const research = loadFixture("I_research_lab");
    expect(canonical.http_status).toBe(200);
    expect(research.http_status).toBe(200);
    expect(validateOperatorSnapshot(canonical.body)).toBe(true);
    expect(validateResearchLabSnapshot(research.body)).toBe(true);
    expect(research._proof?.producer_authority).toBe("RESEARCH_NON_AUTHORITATIVE");
    expect(research._proof?.artifact_is_regular_file).toBe(true);
    expect(research._proof?.population_n).toBe(13);
    expect(research._proof?.candidate_count).toBe(0);

    const fetchMock = vi.fn().mockImplementation((input: RequestInfo | URL) => {
      const url = String(input);
      if (url === "/api/operator/v1/research-lab") {
        return Promise.resolve(jsonResponse(research.body, 200));
      }
      if (url === "/api/operator/v1/snapshot") {
        return Promise.resolve(jsonResponse(canonical.body, 200));
      }
      return Promise.resolve(jsonResponse({ error_code: "UNEXPECTED_TEST_URL" }, 404));
    });
    vi.stubGlobal("fetch", fetchMock);

    render(<App />);
    await waitFor(() => expect(screen.getByTestId("overview-view")).toBeInTheDocument());
    fireEvent.click(screen.getByTestId("tab-research"));

    await waitFor(() =>
      expect(screen.getByTestId("research-domain-banner")).toHaveTextContent(
        "NON-AUTHORITATIVE",
      ),
    );
    const view = screen.getByTestId("research-lab-view");
    expect(view).toHaveTextContent("RESEARCH_NON_AUTHORITATIVE");
    expect(view).toHaveTextContent("LOW_SAMPLE");
    expect(view).toHaveTextContent("annualized_sharpe");
    expect(view).toHaveTextContent("NOT_AVAILABLE");
    expect(view).toHaveTextContent("No certified time-series/annualized return basis.");
    expect(screen.getByTestId("research-candidate-empty")).toHaveTextContent(
      "No substantive candidate",
    );
    expect(fetchMock).toHaveBeenCalledWith(
      "/api/operator/v1/research-lab",
      { method: "GET" },
    );
  });

  it("J U2: exact PPL producer/API burn-in JSON renders governed history without direct JSONL access", async () => {
    const canonical = loadFixture("A_minimal_canonical");
    const burnIn = loadFixture("J_burn_in");
    expect(canonical.http_status).toBe(200);
    expect(burnIn.http_status).toBe(200);
    expect(validateOperatorSnapshot(canonical.body)).toBe(true);
    expect(validateBurnInStatusSnapshot(burnIn.body)).toBe(true);
    expect(burnIn._proof?.producer_authority).toBe("PPL_AUTHORITY_PRESENTATION");
    expect(burnIn._proof?.artifact_is_regular_file).toBe(true);
    expect(burnIn._proof?.ppl_lock_created).toBe(false);
    expect(burnIn._proof?.lifecycle_total).toBe(3);
    expect(burnIn._proof?.history_rows).toBe(3);

    const fetchMock = vi.fn().mockImplementation((input: RequestInfo | URL) => {
      const url = String(input);
      if (url === "/api/operator/v1/burn-in") {
        return Promise.resolve(jsonResponse(burnIn.body, 200));
      }
      if (url === "/api/operator/v1/snapshot") {
        return Promise.resolve(jsonResponse(canonical.body, 200));
      }
      return Promise.resolve(jsonResponse({ error_code: "UNEXPECTED_TEST_URL" }, 404));
    });
    vi.stubGlobal("fetch", fetchMock);

    render(<App />);
    await waitFor(() => expect(screen.getByTestId("overview-view")).toBeInTheDocument());
    fireEvent.click(screen.getByTestId("tab-paper"));
    fireEvent.click(screen.getByTestId("tab-burn-in"));

    await waitFor(() =>
      expect(screen.getByTestId("burnin-view")).toHaveTextContent("BURN-IN-EPOCH-CROSS-STACK"),
    );
    const view = screen.getByTestId("burnin-view");
    expect(view).toHaveTextContent("Historique des ordres PAPER");
    expect(view).toHaveTextContent("BTC/USDT");
    expect(view).toHaveTextContent("ETH/USDT");
    expect(view).toHaveTextContent("SOL/USDT");
    expect(view).toHaveTextContent("UNRESOLVED");
    expect(view).toHaveTextContent("PB_MAX_POSITIONS");
    expect(fetchMock).toHaveBeenCalledWith(
      "/api/operator/v1/burn-in",
      { method: "GET" },
    );
  });

  it("K U2b: exact host producer/API JSON renders independently of a missing Advisor snapshot", async () => {
    const fixture = loadFixture("K_runtime_service");
    expect(fixture.http_status).toBe(200);
    expect(validateRuntimeServiceSnapshot(fixture.body)).toBe(true);
    expect(fixture._proof?.producer_authority).toBe("HOST_SYSTEMD_OBSERVATION");
    expect(fixture._proof?.artifact_is_regular_file).toBe(true);
    expect(fixture._proof?.deployment_evidence_unchanged).toBe(true);
    window.history.replaceState({}, "", "/paper-live/system");
    const fetchMock = vi.fn().mockImplementation((url) => Promise.resolve(String(url).endsWith("/runtime-service") ? jsonResponse(fixture.body, 200) : jsonResponse({ error_code: "SNAPSHOT_MISSING" }, 503)));
    vi.stubGlobal("fetch", fetchMock);
    render(<App />);
    await waitFor(() => expect(screen.getByTestId("runtime-service-view")).toHaveTextContent("host-cross-stack"));
    const view = screen.getByTestId("runtime-service-view");
    expect(view).toHaveTextContent("MainPID à la capture4321");
    expect(view).toHaveTextContent("NRestarts0");
    expect(view).toHaveTextContent("b".repeat(40));
    expect(screen.getByTestId("no-snapshot")).toHaveTextContent("UNRESOLVED");
    expect(fetchMock).toHaveBeenCalledWith("/api/operator/v1/runtime-service", { method: "GET", signal: expect.any(AbortSignal) });
  });

});


describe.skipIf(!HAS_FIXTURES)("U3a scanner real producer → API → React", () => {
  afterEach(() => vi.unstubAllGlobals());
  it("finds and drills into a symbol beyond the old top 20, preserving coverage and source values", async () => {
    const fixture = loadFixture("L_scanner");
    expect(fixture.http_status).toBe(200);
    expect(validateMarketRadarSnapshot(fixture.body)).toBe(true);
    const fetchMock = vi.fn().mockResolvedValue(jsonResponse(fixture.body, 200));
    vi.stubGlobal("fetch", fetchMock);
    render(<MarketView />);
    await waitFor(() => expect(screen.getAllByTestId("market-opportunity-row")).toHaveLength(50));
    expect(screen.getByTestId("market-scanner-coverage")).toHaveTextContent("50 ligne(s) publiée(s) sur 60");
    fireEvent.change(screen.getByLabelText("Recherche symbole"), { target: { value: "s25" } });
    expect(screen.getByTestId("market-opportunity-row")).toHaveTextContent("S25/USDT");
    fireEvent.click(screen.getAllByRole("button", { name: "Détail S25/USDT" })[0]);
    expect(screen.getByTestId("market-symbol-detail")).toHaveTextContent("86.7");
    expect(screen.getByTestId("market-symbol-detail")).toHaveTextContent("SHORT");
    expect(fetchMock).toHaveBeenCalledTimes(1);
  });
});


describe.skipIf(!HAS_FIXTURES)("U3b LMI real producer → API → React", () => {
  afterEach(() => vi.unstubAllGlobals());
  it("accepts the exact microstructure projection and preserves observed, stale and unavailable facts", async () => {
    const fixture = loadFixture("M_microstructure");
    expect(fixture.http_status).toBe(200);
    expect(fixture._proof?.source_unchanged).toBe(true);
    expect(validateMarketMicrostructureSnapshot(fixture.body)).toBe(true);
    vi.stubGlobal("fetch", vi.fn().mockResolvedValue(jsonResponse(fixture.body, 200)));
    render(<MarketMicrostructureView />);
    await waitFor(() => expect(screen.getAllByTestId("microstructure-row")).toHaveLength(3));
    const rows = screen.getAllByTestId("microstructure-row");
    expect(rows[0]).toHaveTextContent("accumulation");
    expect(rows[0]).toHaveTextContent("0,8123");
    expect(rows[1]).toHaveTextContent("STALE");
    expect(rows[2]).toHaveTextContent("NOT_AVAILABLE");
    expect(screen.getByTestId("microstructure-view")).not.toHaveTextContent("GHOSTUSDT");
    expect(screen.getByTestId("microstructure-view")).not.toHaveTextContent("MUST_NOT_ESCAPE");
  });
});
