import type { OperatorSnapshot } from "../types";

export function baseSnapshot(overrides: Partial<OperatorSnapshot> = {}): OperatorSnapshot {
  const snap: OperatorSnapshot = {
    schema_version: "1.0.0",
    snapshot_id: "snap-1",
    cycle: 42,
    process_instance_id: "inst-1",
    generated_at_utc: "2026-09-09T00:00:00+00:00",
    source_sha: "abc123",
    worktree_state: "CLEAN",
    deployment_evidence: {
      status: "VERIFIED",
      source: "deploy_tag",
      evidence_ref: "deploy-20260908-1200",
      observed_at_utc: "2026-09-08T12:00:00+00:00",
    },
    runtime_sha_evidence_status: "VERIFIED",
    portfolio: {
      domain: "portfolio",
      observed_at_utc: "2026-09-09T00:00:00+00:00",
      source: "test",
      freshness: "DEGRADED",
      status: "DEGRADED",
      schema_version: "1.0.0",
      source_version: null,
      evidence: {},
      source_updated_at_utc: { value: null, semantics: "UNKNOWN" },
      authority: "OBSERVATIONAL_TELEMETRY",
      mode: "PAPER",
      paper_equity_usd: { value: 1000, semantics: "PRESENT" },
      paper_open_positions_count: { value: 0, semantics: "ZERO" },
      paper_unrealized_pnl_usd: { value: 0, semantics: "ZERO" },
      paper_realized_pnl_usd: { value: 0, semantics: "ZERO" },
      real_account_equity_usd: { value: null, semantics: "NOT_APPLICABLE" },
      real_account_free_usd: { value: null, semantics: "NOT_APPLICABLE" },
      real_account_stale: { value: null, semantics: "NOT_APPLICABLE" },
      real_account_last_poll_utc: { value: null, semantics: "UNKNOWN" },
      non_paper_wallet_balance_usd: { value: null, semantics: "NOT_APPLICABLE" },
      capital_x_usd: { value: null, semantics: "NOT_APPLICABLE" },
      open_positions: { value: [], semantics: "EMPTY" },
    },
    decision_pipeline: {
      domain: "decision_pipeline",
      observed_at_utc: "2026-09-09T00:00:00+00:00",
      source: "test",
      freshness: "UNKNOWN",
      status: "ATTENTION_REQUIRED",
      schema_version: "1.0.0",
      source_version: null,
      evidence: {},
      source_updated_at_utc: { value: null, semantics: "UNKNOWN" },
      authority: "OBSERVATIONAL_TELEMETRY",
      stages: [],
      trade_allowed: { value: null, semantics: "UNKNOWN" },
      first_blocker: { value: null, semantics: "UNKNOWN" },
      per_symbol_decisions: [],
    },
    system_health: {
      domain: "system_health",
      observed_at_utc: "2026-09-09T00:00:00+00:00",
      source: "test",
      freshness: "UNKNOWN",
      status: "ATTENTION_REQUIRED",
      schema_version: "1.0.0",
      source_version: null,
      evidence: {},
      source_updated_at_utc: { value: null, semantics: "UNKNOWN" },
      authority: "OBSERVATIONAL_TELEMETRY",
      boot_alive: { value: null, semantics: "UNKNOWN" },
      health_score: { value: null, semantics: "UNAVAILABLE" },
      health_level: { value: null, semantics: "UNKNOWN" },
      exchange_connectivity_healthy: { value: null, semantics: "UNAVAILABLE" },
      exchange_latency_ms: { value: null, semantics: "UNAVAILABLE" },
      module_statuses: {},
    },
    instance_relation: "CURRENT_INSTANCE",
    runtime_state: "CURRENT",
    stale_reason: null,
    snapshot_age_s: 1.2,
    freshness_classification: "UNKNOWN",
  };

  return { ...snap, ...overrides };
}
